version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: "pepa-linha-dark"
    ports:
      - 8080:8080